name: Build and Push Docker Image

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'  

    - name: Restore dependencies
      run: dotnet restore ./OnlyBooksApi.csproj  # Substitua por seu arquivo de solução ou projeto

    - name: Build
      run: dotnet build ./OnlyBooksApi.csproj --configuration Release  # Substitua pelo nome do seu arquivo .csproj

    - name: Publish
      run: dotnet publish ./OnlyBooksApi.csproj --configuration Release --output ./publish  # Substitua pelo nome do seu arquivo .csproj

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-api:${{ github.sha }} .
      env:
        DOCKER_BUILDKIT: 1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-api:${{ github.sha }}
